server:
  port: ${PORT:8080}

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    # Si te dan DATABASE_URL estilo: postgres://user:pass@host:port/db
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}?sslmode=require}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1

  jpa:
    hibernate:
      ddl-auto: update   # Para arrancar rápido. En producción, preferible Flyway y ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc.lob.non_contextual_creation: true
    open-in-view: false
  sql:
    init:
      mode: never

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: never
