
# application.properties (solo prod)
server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.directory=logs
server.tomcat.accesslog.pattern=%h %l %u %t "%r" %s %b %D
server.tomcat.basedir=.

# --- DataSource (Postgres Render) ---
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect



# --- HikariCP (Spring Boot usa Hikari por defecto) ---
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.keepalive-time=300000
spring.datasource.hikari.pool-name=solicitudes-pool
spring.datasource.hikari.auto-commit=true

# Enable H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA/Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Micrometer ? Datadog
management.datadog.metrics.export.enabled=true
management.datadog.metrics.export.api-key=${DD_API_KEY}
management.datadog.metrics.export.uri=https://api.us5.datadoghq.com
management.datadog.metrics.export.step=10s

buscador.url=${BUSCADOR_URL}

# Tags globales
management.metrics.tags.service=solicitudes
management.metrics.tags.env=prod
management.metrics.tags.application=Solicitudes

# DevTools Configuration
spring.devtools.restart.enabled=true
